### ISSUE TITLE
UE4 Project will not compile

### ISSUE THREAD

**Issue by seanvail** [Seanv554/leapmotion_boardgame#4]
After using git clone and attempting to open the leapmotion_boardgame project, UE4 says that it cannot compile the project and advises compiling from source manually. Has anyone else encountered this?

**Comment by seanvail** [comment]
Okay, based on Google research, it seems that this has to do with what version of UE4 it was originally compiled in. I'm not sure what version, I was on when I originally compiled it, might be noted somewhere in the project files.

**Comment by seanvail** [comment]
Going to install older versions, attempt to upgrade, and then push the upgraded project onto a new branch.

**Comment by deanljohnson** [comment]
I just got this when trying to move and open the project on my laptop. Everything compiles and runs just fine on my desktop, but my laptop fails with the same error message you seem to have gotten. If I re-download the repository from GitHub onto my desktop I also get the error. That makes it seem like there has to be something different between the two versions I have on my desktop, but I cannot find what that difference is. I'm looking into this more, will post anything I find here.

**Comment by seanvail** [comment]
Tried opening it on version 4.9.2, got the same error, will try 4.8 tomorrow.

**Comment by deanljohnson** [comment]
It seems to be related to a dll file from the third party Leap plugin. Going to try and play around with that and see what happens.

**Comment by seanvail** [comment]
Dean, what version are you running on your Desktop?

**Comment by deanljohnson** [comment]
4.10. 

I think I found the problem. The third party plugin binary is not in the repo, so when you pull the repo without already having it on your computer, UE4 tries to rebuild the binary and fails. I'm going to find out how to edit the gitignore to allow that file in.

**Comment by seanvail** [comment]
Ah, that makes sense, good find. I believe there is someway to add exceptions for specific files in git but I don't know the syntax.

**Comment by deanljohnson** [comment]
Just committed a fix (hopefully).

The syntax for allowing specific files/folders is just ![folder or file name], so I did:

``` text
!Plugins/*/Binaries/*/*
```

The first asterisk would be the plugin name, second is architecture (win64, mac, etc.), and the third asterisk is all the binary files.

I'm going to test the commit on my laptop and see if it works, but I'd prefer if you or Laura tested and closed this issue if it works because I wouldn't be surprised if stuff just magically worked on my machine for some unknown reason.

**Comment by seanvail** [comment]
Confirmed, project compiles successfully! Nice job so far with the grabbing mechanics!
