### ISSUE TITLE
Board Spawning Doesn't Work with Rotated Boards

### ISSUE THREAD

**Issue by deanljohnson** [Seanv554/leapmotion_boardgame#5]
Spawning boards works - as long as the Boards rotation is {0, 0, 0}. Once you start to edit that, all the squares will be placed in wrong positions. Right now this isn't a big deal, but if we eventually create the multiplayer space where there are multiple boards, this will cause us some trouble.

**Comment by seanvail** [comment]
That should be fixable, I just need to pass the Spawner entity's rotation
vector to the BoardSquare entities when I create the transform to spawn
them with.

Sean Vail
Software Quality Assurance Intern
Electric Power Research Institute
Mobile Phone: (760) 271-0231
Work Phone: (650) 858-8910

**Comment by deanljohnson** [comment]
Unfortunately it's not that easy. When I tried that, none of the squares fit together. Something has to be adjusted with regards to world vs. relative positioning. Right now the squares are spawned in their correct world position, and then made children of the Board. What I think needs to be done, is to spawn the squares at the origin with rotation {0, 0, 0}, then attach them to the board with relative positioning. Still not too much work, but it's something I wasn't going to bother working on just yet.

On another note, setting the square's scale to the Board scale did work correctly, allowing the board to be resized as a whole.

**Comment by deanljohnson** [comment]
Fixed this with 94a45497dea40c01b4e7a6c40b9d003c3db4ae53. While doing so I also made sure that pieces had their rotation properly set relative to the boards rotation, and I also set their scale accordingly as well.
